// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvb0QakaZRC0DzPreupaN-2tbKSFLrYtc',
    appId: '1:362955042857:web:bed5172bf2d99695cfec38',
    messagingSenderId: '362955042857',
    projectId: 'update-8eff9',
    authDomain: 'update-8eff9.firebaseapp.com',
    storageBucket: 'update-8eff9.appspot.com',
    measurementId: 'G-X9F35S81PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Nfd3Atmf0rEi5VI89rbuSRw0L6x_hHk',
    appId: '1:362955042857:android:b161ec737e280f5fcfec38',
    messagingSenderId: '362955042857',
    projectId: 'update-8eff9',
    storageBucket: 'update-8eff9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqbB1KlrcQttjzxEn48dy7Tl0hefIiQMo',
    appId: '1:362955042857:ios:d7a791c00dc4de93cfec38',
    messagingSenderId: '362955042857',
    projectId: 'update-8eff9',
    storageBucket: 'update-8eff9.appspot.com',
    iosClientId: '362955042857-0gk39tcgmld8aafo9bjc0djknd1ku3va.apps.googleusercontent.com',
    iosBundleId: 'com.example.update',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqbB1KlrcQttjzxEn48dy7Tl0hefIiQMo',
    appId: '1:362955042857:ios:d7a791c00dc4de93cfec38',
    messagingSenderId: '362955042857',
    projectId: 'update-8eff9',
    storageBucket: 'update-8eff9.appspot.com',
    iosClientId: '362955042857-0gk39tcgmld8aafo9bjc0djknd1ku3va.apps.googleusercontent.com',
    iosBundleId: 'com.example.update',
  );
}
